// <auto-generated />
using System;
using FoodForum.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodForum.Migrations
{
    [DbContext(typeof(FoodForumContext))]
    partial class FoodForumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodForum.Models.Comment", b =>
                {
                    b.Property<int>("RecipeId");

                    b.Property<int>("UserId");

                    b.Property<int>("CommentId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RecipeId", "UserId");

                    b.HasAlternateKey("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FoodForum.Models.Like", b =>
                {
                    b.Property<int>("RecipeId");

                    b.Property<int>("UserId");

                    b.Property<int>("LikeId");

                    b.HasKey("RecipeId", "UserId");

                    b.HasAlternateKey("LikeId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("FoodForum.Models.Rating", b =>
                {
                    b.Property<int>("RecipeId");

                    b.Property<int>("UserId");

                    b.Property<int>("Rate");

                    b.Property<int>("RatingId");

                    b.HasKey("RecipeId", "UserId");

                    b.HasAlternateKey("RatingId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("FoodForum.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2555);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("IngredientEight")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientEleven")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientFifteen")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientFive")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientFour")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientFourteen")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientNine")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientOne")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.Property<string>("IngredientSeven")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientSix")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientTen")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientThirteen")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientThree")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.Property<string>("IngredientTwelve")
                        .HasMaxLength(65);

                    b.Property<string>("IngredientTwo")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.Property<string>("PictureURL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(55);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Recipe");
                });

            modelBuilder.Entity("FoodForum.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminState");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodForum.Models.AdminRecipe", b =>
                {
                    b.HasBaseType("FoodForum.Models.Recipe");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.ToTable("AdminRecipe");

                    b.HasDiscriminator().HasValue("AdminRecipe");
                });

            modelBuilder.Entity("FoodForum.Models.UserRecipe", b =>
                {
                    b.HasBaseType("FoodForum.Models.Recipe");


                    b.ToTable("UserRecipe");

                    b.HasDiscriminator().HasValue("UserRecipe");
                });

            modelBuilder.Entity("FoodForum.Models.Comment", b =>
                {
                    b.HasOne("FoodForum.Models.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FoodForum.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FoodForum.Models.Like", b =>
                {
                    b.HasOne("FoodForum.Models.Recipe", "Recipe")
                        .WithMany("Likes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FoodForum.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FoodForum.Models.Rating", b =>
                {
                    b.HasOne("FoodForum.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FoodForum.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FoodForum.Models.Recipe", b =>
                {
                    b.HasOne("FoodForum.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
